# -*- coding: utf-8 -*-
"""dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ejgty29i6CIwdwx9g22t2EC23oqQ01a9
"""

# Membuat aplikasi Streamlit
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Memuat data dari file CSV
data = pd.read_csv("D:/Bangkit/Dicoding/submission/dasboard/all_data.csv")

# Judul Aplikasi
st.title("Dashboard Data")

# Tampilkan Data
st.subheader("Data Table")
st.dataframe(data)

# Statistik Deskriptif
st.subheader("Descriptive Statistics")
st.write(data.describe())

# Visualisasi Histogram kolom pertama
st.subheader("Distribusi Kolom Pertama")
plt.figure(figsize=(10, 6))
sns.histplot(data.iloc[:, 0], kde=True)
st.pyplot(plt)

# Visualisasi Scatter plot dua kolom pertama
st.subheader("Scatter Plot (Dua Kolom Pertama)")
plt.figure(figsize=(10, 6))
sns.scatterplot(x=data.columns[0], y=data.columns[1], data=data)
st.pyplot(plt)